# Generated by Django 5.1.3 on 2024-11-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_restablecimiento',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
