# Generated by Django 5.1.3 on 2024-11-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_codigo_restablecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
